toc:
- title: "Class Index"
  path: "/reference/androidx/classes.html"

- title: "Package Index"
  path: "/reference/androidx/packages.html"

- title: "androidx.compose.animation"
  path: "/reference/androidx/compose/animation/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "AnimatedVisibilityScope"
      path: "/reference/androidx/compose/animation/AnimatedVisibilityScope.html"
    - title: "SizeTransform"
      path: "/reference/androidx/compose/animation/SizeTransform.html"

  - title: "Classes"

    section:
    - title: "AndroidActualDefaultDecayAnimationSpecKt"
      path: "/reference/androidx/compose/animation/AndroidActualDefaultDecayAnimationSpecKt.html"
    - title: "AnimatedContentKt"
      path: "/reference/androidx/compose/animation/AnimatedContentKt.html"
    - title: "AnimatedContentScope"
      path: "/reference/androidx/compose/animation/AnimatedContentScope.html"
    - title: "AnimatedContentScope.SlideDirection"
      path: "/reference/androidx/compose/animation/AnimatedContentScope.SlideDirection.html"
    - title: "AnimatedVisibilityKt"
      path: "/reference/androidx/compose/animation/AnimatedVisibilityKt.html"
    - title: "AnimationModifierKt"
      path: "/reference/androidx/compose/animation/AnimationModifierKt.html"
    - title: "ColorVectorConverterKt"
      path: "/reference/androidx/compose/animation/ColorVectorConverterKt.html"
    - title: "ContentTransform"
      path: "/reference/androidx/compose/animation/ContentTransform.html"
    - title: "CrossfadeKt"
      path: "/reference/androidx/compose/animation/CrossfadeKt.html"
    - title: "DefaultDecayAnimationSpecKt"
      path: "/reference/androidx/compose/animation/DefaultDecayAnimationSpecKt.html"
    - title: "EnterExitTransitionKt"
      path: "/reference/androidx/compose/animation/EnterExitTransitionKt.html"
    - title: "EnterTransition"
      path: "/reference/androidx/compose/animation/EnterTransition.html"
    - title: "ExitTransition"
      path: "/reference/androidx/compose/animation/ExitTransition.html"
    - title: "SingleValueAnimationKt"
      path: "/reference/androidx/compose/animation/SingleValueAnimationKt.html"
    - title: "SplineBasedDecayKt"
      path: "/reference/androidx/compose/animation/SplineBasedDecayKt.html"
    - title: "SplineBasedFloatDecayAnimationSpec"
      path: "/reference/androidx/compose/animation/SplineBasedFloatDecayAnimationSpec.html"
    - title: "SplineBasedFloatDecayAnimationSpecKt"
      path: "/reference/androidx/compose/animation/SplineBasedFloatDecayAnimationSpecKt.html"
    - title: "TransitionKt"
      path: "/reference/androidx/compose/animation/TransitionKt.html"

  - title: "Enums"

    section:
    - title: "EnterExitState"
      path: "/reference/androidx/compose/animation/EnterExitState.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalAnimationApi"
      path: "/reference/androidx/compose/animation/ExperimentalAnimationApi.html"

- title: "androidx.compose.animation.core"
  path: "/reference/androidx/compose/animation/core/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Animation"
      path: "/reference/androidx/compose/animation/core/Animation.html"
    - title: "AnimationSpec"
      path: "/reference/androidx/compose/animation/core/AnimationSpec.html"
    - title: "DecayAnimationSpec"
      path: "/reference/androidx/compose/animation/core/DecayAnimationSpec.html"
    - title: "DurationBasedAnimationSpec"
      path: "/reference/androidx/compose/animation/core/DurationBasedAnimationSpec.html"
    - title: "Easing"
      path: "/reference/androidx/compose/animation/core/Easing.html"
    - title: "FiniteAnimationSpec"
      path: "/reference/androidx/compose/animation/core/FiniteAnimationSpec.html"
    - title: "FloatAnimationSpec"
      path: "/reference/androidx/compose/animation/core/FloatAnimationSpec.html"
    - title: "FloatDecayAnimationSpec"
      path: "/reference/androidx/compose/animation/core/FloatDecayAnimationSpec.html"
    - title: "InfiniteAnimationPolicy"
      path: "/reference/androidx/compose/animation/core/InfiniteAnimationPolicy.html"
    - title: "Transition.Segment"
      path: "/reference/androidx/compose/animation/core/Transition.Segment.html"
    - title: "TwoWayConverter"
      path: "/reference/androidx/compose/animation/core/TwoWayConverter.html"
    - title: "VectorizedAnimationSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedAnimationSpec.html"
    - title: "VectorizedDecayAnimationSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedDecayAnimationSpec.html"
    - title: "VectorizedDurationBasedAnimationSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedDurationBasedAnimationSpec.html"
    - title: "VectorizedFiniteAnimationSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedFiniteAnimationSpec.html"

  - title: "Classes"

    section:
    - title: "Animatable"
      path: "/reference/androidx/compose/animation/core/Animatable.html"
    - title: "AnimatableKt"
      path: "/reference/androidx/compose/animation/core/AnimatableKt.html"
    - title: "AnimateAsStateKt"
      path: "/reference/androidx/compose/animation/core/AnimateAsStateKt.html"
    - title: "AnimationKt"
      path: "/reference/androidx/compose/animation/core/AnimationKt.html"
    - title: "AnimationResult"
      path: "/reference/androidx/compose/animation/core/AnimationResult.html"
    - title: "AnimationScope"
      path: "/reference/androidx/compose/animation/core/AnimationScope.html"
    - title: "AnimationSpecKt"
      path: "/reference/androidx/compose/animation/core/AnimationSpecKt.html"
    - title: "AnimationState"
      path: "/reference/androidx/compose/animation/core/AnimationState.html"
    - title: "AnimationStateKt"
      path: "/reference/androidx/compose/animation/core/AnimationStateKt.html"
    - title: "AnimationVector"
      path: "/reference/androidx/compose/animation/core/AnimationVector.html"
    - title: "AnimationVector1D"
      path: "/reference/androidx/compose/animation/core/AnimationVector1D.html"
    - title: "AnimationVector2D"
      path: "/reference/androidx/compose/animation/core/AnimationVector2D.html"
    - title: "AnimationVector3D"
      path: "/reference/androidx/compose/animation/core/AnimationVector3D.html"
    - title: "AnimationVector4D"
      path: "/reference/androidx/compose/animation/core/AnimationVector4D.html"
    - title: "AnimationVectorsKt"
      path: "/reference/androidx/compose/animation/core/AnimationVectorsKt.html"
    - title: "AtomicReference"
      path: "/reference/androidx/compose/animation/core/AtomicReference.html"
    - title: "CubicBezierEasing"
      path: "/reference/androidx/compose/animation/core/CubicBezierEasing.html"
    - title: "DecayAnimation"
      path: "/reference/androidx/compose/animation/core/DecayAnimation.html"
    - title: "DecayAnimationSpecKt"
      path: "/reference/androidx/compose/animation/core/DecayAnimationSpecKt.html"
    - title: "EasingKt"
      path: "/reference/androidx/compose/animation/core/EasingKt.html"
    - title: "FloatExponentialDecaySpec"
      path: "/reference/androidx/compose/animation/core/FloatExponentialDecaySpec.html"
    - title: "FloatSpringSpec"
      path: "/reference/androidx/compose/animation/core/FloatSpringSpec.html"
    - title: "FloatTweenSpec"
      path: "/reference/androidx/compose/animation/core/FloatTweenSpec.html"
    - title: "InfiniteAnimationPolicyKt"
      path: "/reference/androidx/compose/animation/core/InfiniteAnimationPolicyKt.html"
    - title: "InfiniteRepeatableSpec"
      path: "/reference/androidx/compose/animation/core/InfiniteRepeatableSpec.html"
    - title: "InfiniteTransition"
      path: "/reference/androidx/compose/animation/core/InfiniteTransition.html"
    - title: "InfiniteTransitionKt"
      path: "/reference/androidx/compose/animation/core/InfiniteTransitionKt.html"
    - title: "KeyframesSpec"
      path: "/reference/androidx/compose/animation/core/KeyframesSpec.html"
    - title: "KeyframesSpec.KeyframeEntity"
      path: "/reference/androidx/compose/animation/core/KeyframesSpec.KeyframeEntity.html"
    - title: "KeyframesSpec.KeyframesSpecConfig"
      path: "/reference/androidx/compose/animation/core/KeyframesSpec.KeyframesSpecConfig.html"
    - title: "MutableTransitionState"
      path: "/reference/androidx/compose/animation/core/MutableTransitionState.html"
    - title: "RepeatableSpec"
      path: "/reference/androidx/compose/animation/core/RepeatableSpec.html"
    - title: "SnapSpec"
      path: "/reference/androidx/compose/animation/core/SnapSpec.html"
    - title: "SpringSpec"
      path: "/reference/androidx/compose/animation/core/SpringSpec.html"
    - title: "SuspendAnimationKt"
      path: "/reference/androidx/compose/animation/core/SuspendAnimationKt.html"
    - title: "TargetBasedAnimation"
      path: "/reference/androidx/compose/animation/core/TargetBasedAnimation.html"
    - title: "Transition"
      path: "/reference/androidx/compose/animation/core/Transition.html"
    - title: "TransitionKt"
      path: "/reference/androidx/compose/animation/core/TransitionKt.html"
    - title: "TweenSpec"
      path: "/reference/androidx/compose/animation/core/TweenSpec.html"
    - title: "VectorConvertersKt"
      path: "/reference/androidx/compose/animation/core/VectorConvertersKt.html"
    - title: "VectorizedFloatAnimationSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedFloatAnimationSpec.html"
    - title: "VectorizedInfiniteRepeatableSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedInfiniteRepeatableSpec.html"
    - title: "VectorizedKeyframesSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedKeyframesSpec.html"
    - title: "VectorizedRepeatableSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedRepeatableSpec.html"
    - title: "VectorizedSnapSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedSnapSpec.html"
    - title: "VectorizedSpringSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedSpringSpec.html"
    - title: "VectorizedTweenSpec"
      path: "/reference/androidx/compose/animation/core/VectorizedTweenSpec.html"
    - title: "VisibilityThresholdsKt"
      path: "/reference/androidx/compose/animation/core/VisibilityThresholdsKt.html"

  - title: "Enums"

    section:
    - title: "AnimationEndReason"
      path: "/reference/androidx/compose/animation/core/AnimationEndReason.html"
    - title: "RepeatMode"
      path: "/reference/androidx/compose/animation/core/RepeatMode.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalTransitionApi"
      path: "/reference/androidx/compose/animation/core/ExperimentalTransitionApi.html"
    - title: "InternalAnimationApi"
      path: "/reference/androidx/compose/animation/core/InternalAnimationApi.html"

- title: "androidx.compose.foundation"
  path: "/reference/androidx/compose/foundation/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Indication"
      path: "/reference/androidx/compose/foundation/Indication.html"
    - title: "IndicationInstance"
      path: "/reference/androidx/compose/foundation/IndicationInstance.html"

  - title: "Classes"

    section:
    - title: "AtomicLong"
      path: "/reference/androidx/compose/foundation/AtomicLong.html"
    - title: "AtomicReference"
      path: "/reference/androidx/compose/foundation/AtomicReference.html"
    - title: "BackgroundKt"
      path: "/reference/androidx/compose/foundation/BackgroundKt.html"
    - title: "BorderKt"
      path: "/reference/androidx/compose/foundation/BorderKt.html"
    - title: "BorderStroke"
      path: "/reference/androidx/compose/foundation/BorderStroke.html"
    - title: "BorderStrokeKt"
      path: "/reference/androidx/compose/foundation/BorderStrokeKt.html"
    - title: "CanvasKt"
      path: "/reference/androidx/compose/foundation/CanvasKt.html"
    - title: "ClickableKt"
      path: "/reference/androidx/compose/foundation/ClickableKt.html"
    - title: "DarkThemeKt"
      path: "/reference/androidx/compose/foundation/DarkThemeKt.html"
    - title: "FocusableKt"
      path: "/reference/androidx/compose/foundation/FocusableKt.html"
    - title: "ImageKt"
      path: "/reference/androidx/compose/foundation/ImageKt.html"
    - title: "IndicationKt"
      path: "/reference/androidx/compose/foundation/IndicationKt.html"
    - title: "MutatorMutex"
      path: "/reference/androidx/compose/foundation/MutatorMutex.html"
    - title: "ProgressSemanticsKt"
      path: "/reference/androidx/compose/foundation/ProgressSemanticsKt.html"
    - title: "ScrollKt"
      path: "/reference/androidx/compose/foundation/ScrollKt.html"
    - title: "ScrollState"
      path: "/reference/androidx/compose/foundation/ScrollState.html"

  - title: "Enums"

    section:
    - title: "MutatePriority"
      path: "/reference/androidx/compose/foundation/MutatePriority.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalFoundationApi"
      path: "/reference/androidx/compose/foundation/ExperimentalFoundationApi.html"
    - title: "InternalFoundationApi"
      path: "/reference/androidx/compose/foundation/InternalFoundationApi.html"

- title: "androidx.compose.foundation.gestures"
  path: "/reference/androidx/compose/foundation/gestures/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "DragScope"
      path: "/reference/androidx/compose/foundation/gestures/DragScope.html"
    - title: "DraggableState"
      path: "/reference/androidx/compose/foundation/gestures/DraggableState.html"
    - title: "FlingBehavior"
      path: "/reference/androidx/compose/foundation/gestures/FlingBehavior.html"
    - title: "PressGestureScope"
      path: "/reference/androidx/compose/foundation/gestures/PressGestureScope.html"
    - title: "ScrollScope"
      path: "/reference/androidx/compose/foundation/gestures/ScrollScope.html"
    - title: "ScrollableState"
      path: "/reference/androidx/compose/foundation/gestures/ScrollableState.html"
    - title: "TransformScope"
      path: "/reference/androidx/compose/foundation/gestures/TransformScope.html"
    - title: "TransformableState"
      path: "/reference/androidx/compose/foundation/gestures/TransformableState.html"

  - title: "Classes"

    section:
    - title: "DragGestureDetectorKt"
      path: "/reference/androidx/compose/foundation/gestures/DragGestureDetectorKt.html"
    - title: "DraggableKt"
      path: "/reference/androidx/compose/foundation/gestures/DraggableKt.html"
    - title: "ForEachGestureKt"
      path: "/reference/androidx/compose/foundation/gestures/ForEachGestureKt.html"
    - title: "ScrollExtensionsKt"
      path: "/reference/androidx/compose/foundation/gestures/ScrollExtensionsKt.html"
    - title: "ScrollableKt"
      path: "/reference/androidx/compose/foundation/gestures/ScrollableKt.html"
    - title: "ScrollableStateKt"
      path: "/reference/androidx/compose/foundation/gestures/ScrollableStateKt.html"
    - title: "TapGestureDetectorKt"
      path: "/reference/androidx/compose/foundation/gestures/TapGestureDetectorKt.html"
    - title: "TransformGestureDetectorKt"
      path: "/reference/androidx/compose/foundation/gestures/TransformGestureDetectorKt.html"
    - title: "TransformableKt"
      path: "/reference/androidx/compose/foundation/gestures/TransformableKt.html"
    - title: "TransformableStateKt"
      path: "/reference/androidx/compose/foundation/gestures/TransformableStateKt.html"

  - title: "Enums"

    section:
    - title: "Orientation"
      path: "/reference/androidx/compose/foundation/gestures/Orientation.html"

  - title: "Exceptions"

    section:
    - title: "GestureCancellationException"
      path: "/reference/androidx/compose/foundation/gestures/GestureCancellationException.html"

- title: "androidx.compose.foundation.interaction"
  path: "/reference/androidx/compose/foundation/interaction/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "DragInteraction"
      path: "/reference/androidx/compose/foundation/interaction/DragInteraction.html"
    - title: "FocusInteraction"
      path: "/reference/androidx/compose/foundation/interaction/FocusInteraction.html"
    - title: "Interaction"
      path: "/reference/androidx/compose/foundation/interaction/Interaction.html"
    - title: "InteractionSource"
      path: "/reference/androidx/compose/foundation/interaction/InteractionSource.html"
    - title: "MutableInteractionSource"
      path: "/reference/androidx/compose/foundation/interaction/MutableInteractionSource.html"
    - title: "PressInteraction"
      path: "/reference/androidx/compose/foundation/interaction/PressInteraction.html"

  - title: "Classes"

    section:
    - title: "DragInteraction.Cancel"
      path: "/reference/androidx/compose/foundation/interaction/DragInteraction.Cancel.html"
    - title: "DragInteraction.Start"
      path: "/reference/androidx/compose/foundation/interaction/DragInteraction.Start.html"
    - title: "DragInteraction.Stop"
      path: "/reference/androidx/compose/foundation/interaction/DragInteraction.Stop.html"
    - title: "DragInteractionKt"
      path: "/reference/androidx/compose/foundation/interaction/DragInteractionKt.html"
    - title: "FocusInteraction.Focus"
      path: "/reference/androidx/compose/foundation/interaction/FocusInteraction.Focus.html"
    - title: "FocusInteraction.Unfocus"
      path: "/reference/androidx/compose/foundation/interaction/FocusInteraction.Unfocus.html"
    - title: "FocusInteractionKt"
      path: "/reference/androidx/compose/foundation/interaction/FocusInteractionKt.html"
    - title: "InteractionSourceKt"
      path: "/reference/androidx/compose/foundation/interaction/InteractionSourceKt.html"
    - title: "PressInteraction.Cancel"
      path: "/reference/androidx/compose/foundation/interaction/PressInteraction.Cancel.html"
    - title: "PressInteraction.Press"
      path: "/reference/androidx/compose/foundation/interaction/PressInteraction.Press.html"
    - title: "PressInteraction.Release"
      path: "/reference/androidx/compose/foundation/interaction/PressInteraction.Release.html"
    - title: "PressInteractionKt"
      path: "/reference/androidx/compose/foundation/interaction/PressInteractionKt.html"

- title: "androidx.compose.foundation.layout"
  path: "/reference/androidx/compose/foundation/layout/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Arrangement.Horizontal"
      path: "/reference/androidx/compose/foundation/layout/Arrangement.Horizontal.html"
    - title: "Arrangement.HorizontalOrVertical"
      path: "/reference/androidx/compose/foundation/layout/Arrangement.HorizontalOrVertical.html"
    - title: "Arrangement.Vertical"
      path: "/reference/androidx/compose/foundation/layout/Arrangement.Vertical.html"
    - title: "BoxScope"
      path: "/reference/androidx/compose/foundation/layout/BoxScope.html"
    - title: "BoxWithConstraintsScope"
      path: "/reference/androidx/compose/foundation/layout/BoxWithConstraintsScope.html"
    - title: "ColumnScope"
      path: "/reference/androidx/compose/foundation/layout/ColumnScope.html"
    - title: "PaddingValues"
      path: "/reference/androidx/compose/foundation/layout/PaddingValues.html"
    - title: "RowScope"
      path: "/reference/androidx/compose/foundation/layout/RowScope.html"

  - title: "Classes"

    section:
    - title: "AlignmentLineKt"
      path: "/reference/androidx/compose/foundation/layout/AlignmentLineKt.html"
    - title: "AspectRatioKt"
      path: "/reference/androidx/compose/foundation/layout/AspectRatioKt.html"
    - title: "BoxKt"
      path: "/reference/androidx/compose/foundation/layout/BoxKt.html"
    - title: "BoxWithConstraintsKt"
      path: "/reference/androidx/compose/foundation/layout/BoxWithConstraintsKt.html"
    - title: "ColumnKt"
      path: "/reference/androidx/compose/foundation/layout/ColumnKt.html"
    - title: "IntrinsicKt"
      path: "/reference/androidx/compose/foundation/layout/IntrinsicKt.html"
    - title: "OffsetKt"
      path: "/reference/androidx/compose/foundation/layout/OffsetKt.html"
    - title: "PaddingKt"
      path: "/reference/androidx/compose/foundation/layout/PaddingKt.html"
    - title: "PaddingValues.Absolute"
      path: "/reference/androidx/compose/foundation/layout/PaddingValues.Absolute.html"
    - title: "RowKt"
      path: "/reference/androidx/compose/foundation/layout/RowKt.html"
    - title: "SizeKt"
      path: "/reference/androidx/compose/foundation/layout/SizeKt.html"
    - title: "SpacerKt"
      path: "/reference/androidx/compose/foundation/layout/SpacerKt.html"

  - title: "Enums"

    section:
    - title: "IntrinsicSize"
      path: "/reference/androidx/compose/foundation/layout/IntrinsicSize.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalLayoutApi"
      path: "/reference/androidx/compose/foundation/layout/ExperimentalLayoutApi.html"
    - title: "LayoutScopeMarker"
      path: "/reference/androidx/compose/foundation/layout/LayoutScopeMarker.html"

- title: "androidx.compose.foundation.lazy"
  path: "/reference/androidx/compose/foundation/lazy/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "LazyGridScope"
      path: "/reference/androidx/compose/foundation/lazy/LazyGridScope.html"
    - title: "LazyItemScope"
      path: "/reference/androidx/compose/foundation/lazy/LazyItemScope.html"
    - title: "LazyListItemInfo"
      path: "/reference/androidx/compose/foundation/lazy/LazyListItemInfo.html"
    - title: "LazyListLayoutInfo"
      path: "/reference/androidx/compose/foundation/lazy/LazyListLayoutInfo.html"
    - title: "LazyListScope"
      path: "/reference/androidx/compose/foundation/lazy/LazyListScope.html"

  - title: "Classes"

    section:
    - title: "GridCells"
      path: "/reference/androidx/compose/foundation/lazy/GridCells.html"
    - title: "GridCells.Adaptive"
      path: "/reference/androidx/compose/foundation/lazy/GridCells.Adaptive.html"
    - title: "GridCells.Fixed"
      path: "/reference/androidx/compose/foundation/lazy/GridCells.Fixed.html"
    - title: "LazyDslKt"
      path: "/reference/androidx/compose/foundation/lazy/LazyDslKt.html"
    - title: "LazyGridKt"
      path: "/reference/androidx/compose/foundation/lazy/LazyGridKt.html"
    - title: "LazyListState"
      path: "/reference/androidx/compose/foundation/lazy/LazyListState.html"
    - title: "LazyListStateKt"
      path: "/reference/androidx/compose/foundation/lazy/LazyListStateKt.html"

  - title: "Annotations"

    section:
    - title: "LazyScopeMarker"
      path: "/reference/androidx/compose/foundation/lazy/LazyScopeMarker.html"

- title: "androidx.compose.foundation.selection"
  path: "/reference/androidx/compose/foundation/selection/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "SelectableGroupKt"
      path: "/reference/androidx/compose/foundation/selection/SelectableGroupKt.html"
    - title: "SelectableKt"
      path: "/reference/androidx/compose/foundation/selection/SelectableKt.html"
    - title: "ToggleableKt"
      path: "/reference/androidx/compose/foundation/selection/ToggleableKt.html"

- title: "androidx.compose.foundation.shape"
  path: "/reference/androidx/compose/foundation/shape/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "CornerSize"
      path: "/reference/androidx/compose/foundation/shape/CornerSize.html"

  - title: "Classes"

    section:
    - title: "AbsoluteCutCornerShape"
      path: "/reference/androidx/compose/foundation/shape/AbsoluteCutCornerShape.html"
    - title: "AbsoluteCutCornerShapeKt"
      path: "/reference/androidx/compose/foundation/shape/AbsoluteCutCornerShapeKt.html"
    - title: "AbsoluteRoundedCornerShape"
      path: "/reference/androidx/compose/foundation/shape/AbsoluteRoundedCornerShape.html"
    - title: "AbsoluteRoundedCornerShapeKt"
      path: "/reference/androidx/compose/foundation/shape/AbsoluteRoundedCornerShapeKt.html"
    - title: "CornerBasedShape"
      path: "/reference/androidx/compose/foundation/shape/CornerBasedShape.html"
    - title: "CornerSizeKt"
      path: "/reference/androidx/compose/foundation/shape/CornerSizeKt.html"
    - title: "CutCornerShape"
      path: "/reference/androidx/compose/foundation/shape/CutCornerShape.html"
    - title: "CutCornerShapeKt"
      path: "/reference/androidx/compose/foundation/shape/CutCornerShapeKt.html"
    - title: "GenericShape"
      path: "/reference/androidx/compose/foundation/shape/GenericShape.html"
    - title: "RoundedCornerShape"
      path: "/reference/androidx/compose/foundation/shape/RoundedCornerShape.html"
    - title: "RoundedCornerShapeKt"
      path: "/reference/androidx/compose/foundation/shape/RoundedCornerShapeKt.html"

- title: "androidx.compose.foundation.text"
  path: "/reference/androidx/compose/foundation/text/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "KeyboardActionScope"
      path: "/reference/androidx/compose/foundation/text/KeyboardActionScope.html"

  - title: "Classes"

    section:
    - title: "BasicTextFieldKt"
      path: "/reference/androidx/compose/foundation/text/BasicTextFieldKt.html"
    - title: "BasicTextKt"
      path: "/reference/androidx/compose/foundation/text/BasicTextKt.html"
    - title: "ClickableTextKt"
      path: "/reference/androidx/compose/foundation/text/ClickableTextKt.html"
    - title: "InlineTextContent"
      path: "/reference/androidx/compose/foundation/text/InlineTextContent.html"
    - title: "InlineTextContentKt"
      path: "/reference/androidx/compose/foundation/text/InlineTextContentKt.html"
    - title: "KeyboardActions"
      path: "/reference/androidx/compose/foundation/text/KeyboardActions.html"
    - title: "KeyboardActionsKt"
      path: "/reference/androidx/compose/foundation/text/KeyboardActionsKt.html"
    - title: "KeyboardOptions"
      path: "/reference/androidx/compose/foundation/text/KeyboardOptions.html"

  - title: "Annotations"

    section:
    - title: "InternalFoundationTextApi"
      path: "/reference/androidx/compose/foundation/text/InternalFoundationTextApi.html"

- title: "androidx.compose.foundation.text.selection"
  path: "/reference/androidx/compose/foundation/text/selection/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "SelectionContainerKt"
      path: "/reference/androidx/compose/foundation/text/selection/SelectionContainerKt.html"
    - title: "TextSelectionColors"
      path: "/reference/androidx/compose/foundation/text/selection/TextSelectionColors.html"
    - title: "TextSelectionColorsKt"
      path: "/reference/androidx/compose/foundation/text/selection/TextSelectionColorsKt.html"

- title: "androidx.compose.material"
  path: "/reference/androidx/compose/material/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "ButtonColors"
      path: "/reference/androidx/compose/material/ButtonColors.html"
    - title: "ButtonElevation"
      path: "/reference/androidx/compose/material/ButtonElevation.html"
    - title: "CheckboxColors"
      path: "/reference/androidx/compose/material/CheckboxColors.html"
    - title: "ElevationOverlay"
      path: "/reference/androidx/compose/material/ElevationOverlay.html"
    - title: "FloatingActionButtonElevation"
      path: "/reference/androidx/compose/material/FloatingActionButtonElevation.html"
    - title: "RadioButtonColors"
      path: "/reference/androidx/compose/material/RadioButtonColors.html"
    - title: "SliderColors"
      path: "/reference/androidx/compose/material/SliderColors.html"
    - title: "SnackbarData"
      path: "/reference/androidx/compose/material/SnackbarData.html"
    - title: "SwitchColors"
      path: "/reference/androidx/compose/material/SwitchColors.html"
    - title: "TextFieldColors"
      path: "/reference/androidx/compose/material/TextFieldColors.html"
    - title: "ThresholdConfig"
      path: "/reference/androidx/compose/material/ThresholdConfig.html"

  - title: "Classes"

    section:
    - title: "AndroidAlertDialogKt"
      path: "/reference/androidx/compose/material/AndroidAlertDialogKt.html"
    - title: "AndroidMenuKt"
      path: "/reference/androidx/compose/material/AndroidMenuKt.html"
    - title: "AppBarKt"
      path: "/reference/androidx/compose/material/AppBarKt.html"
    - title: "BackdropScaffoldKt"
      path: "/reference/androidx/compose/material/BackdropScaffoldKt.html"
    - title: "BackdropScaffoldState"
      path: "/reference/androidx/compose/material/BackdropScaffoldState.html"
    - title: "BottomDrawerState"
      path: "/reference/androidx/compose/material/BottomDrawerState.html"
    - title: "BottomNavigationKt"
      path: "/reference/androidx/compose/material/BottomNavigationKt.html"
    - title: "BottomSheetScaffoldKt"
      path: "/reference/androidx/compose/material/BottomSheetScaffoldKt.html"
    - title: "BottomSheetScaffoldState"
      path: "/reference/androidx/compose/material/BottomSheetScaffoldState.html"
    - title: "BottomSheetState"
      path: "/reference/androidx/compose/material/BottomSheetState.html"
    - title: "ButtonKt"
      path: "/reference/androidx/compose/material/ButtonKt.html"
    - title: "CardKt"
      path: "/reference/androidx/compose/material/CardKt.html"
    - title: "CheckboxKt"
      path: "/reference/androidx/compose/material/CheckboxKt.html"
    - title: "Colors"
      path: "/reference/androidx/compose/material/Colors.html"
    - title: "ColorsKt"
      path: "/reference/androidx/compose/material/ColorsKt.html"
    - title: "ContentAlphaKt"
      path: "/reference/androidx/compose/material/ContentAlphaKt.html"
    - title: "ContentColorKt"
      path: "/reference/androidx/compose/material/ContentColorKt.html"
    - title: "DismissState"
      path: "/reference/androidx/compose/material/DismissState.html"
    - title: "DividerKt"
      path: "/reference/androidx/compose/material/DividerKt.html"
    - title: "DrawerKt"
      path: "/reference/androidx/compose/material/DrawerKt.html"
    - title: "DrawerState"
      path: "/reference/androidx/compose/material/DrawerState.html"
    - title: "ElevationOverlayKt"
      path: "/reference/androidx/compose/material/ElevationOverlayKt.html"
    - title: "FabPosition"
      path: "/reference/androidx/compose/material/FabPosition.html"
    - title: "FixedThreshold"
      path: "/reference/androidx/compose/material/FixedThreshold.html"
    - title: "FloatingActionButtonKt"
      path: "/reference/androidx/compose/material/FloatingActionButtonKt.html"
    - title: "FractionalThreshold"
      path: "/reference/androidx/compose/material/FractionalThreshold.html"
    - title: "IconButtonKt"
      path: "/reference/androidx/compose/material/IconButtonKt.html"
    - title: "IconKt"
      path: "/reference/androidx/compose/material/IconKt.html"
    - title: "ListItemKt"
      path: "/reference/androidx/compose/material/ListItemKt.html"
    - title: "MaterialThemeKt"
      path: "/reference/androidx/compose/material/MaterialThemeKt.html"
    - title: "ModalBottomSheetKt"
      path: "/reference/androidx/compose/material/ModalBottomSheetKt.html"
    - title: "ModalBottomSheetState"
      path: "/reference/androidx/compose/material/ModalBottomSheetState.html"
    - title: "OutlinedTextFieldKt"
      path: "/reference/androidx/compose/material/OutlinedTextFieldKt.html"
    - title: "ProgressIndicatorKt"
      path: "/reference/androidx/compose/material/ProgressIndicatorKt.html"
    - title: "RadioButtonKt"
      path: "/reference/androidx/compose/material/RadioButtonKt.html"
    - title: "ResistanceConfig"
      path: "/reference/androidx/compose/material/ResistanceConfig.html"
    - title: "ScaffoldKt"
      path: "/reference/androidx/compose/material/ScaffoldKt.html"
    - title: "ScaffoldState"
      path: "/reference/androidx/compose/material/ScaffoldState.html"
    - title: "Shapes"
      path: "/reference/androidx/compose/material/Shapes.html"
    - title: "SliderKt"
      path: "/reference/androidx/compose/material/SliderKt.html"
    - title: "SnackbarHostKt"
      path: "/reference/androidx/compose/material/SnackbarHostKt.html"
    - title: "SnackbarHostState"
      path: "/reference/androidx/compose/material/SnackbarHostState.html"
    - title: "SnackbarKt"
      path: "/reference/androidx/compose/material/SnackbarKt.html"
    - title: "SurfaceKt"
      path: "/reference/androidx/compose/material/SurfaceKt.html"
    - title: "SwipeProgress"
      path: "/reference/androidx/compose/material/SwipeProgress.html"
    - title: "SwipeToDismissKt"
      path: "/reference/androidx/compose/material/SwipeToDismissKt.html"
    - title: "SwipeableKt"
      path: "/reference/androidx/compose/material/SwipeableKt.html"
    - title: "SwipeableState"
      path: "/reference/androidx/compose/material/SwipeableState.html"
    - title: "SwitchKt"
      path: "/reference/androidx/compose/material/SwitchKt.html"
    - title: "TabKt"
      path: "/reference/androidx/compose/material/TabKt.html"
    - title: "TabPosition"
      path: "/reference/androidx/compose/material/TabPosition.html"
    - title: "TabRowKt"
      path: "/reference/androidx/compose/material/TabRowKt.html"
    - title: "TextFieldKt"
      path: "/reference/androidx/compose/material/TextFieldKt.html"
    - title: "TextKt"
      path: "/reference/androidx/compose/material/TextKt.html"
    - title: "Typography"
      path: "/reference/androidx/compose/material/Typography.html"

  - title: "Enums"

    section:
    - title: "BackdropValue"
      path: "/reference/androidx/compose/material/BackdropValue.html"
    - title: "BottomDrawerValue"
      path: "/reference/androidx/compose/material/BottomDrawerValue.html"
    - title: "BottomSheetValue"
      path: "/reference/androidx/compose/material/BottomSheetValue.html"
    - title: "DismissDirection"
      path: "/reference/androidx/compose/material/DismissDirection.html"
    - title: "DismissValue"
      path: "/reference/androidx/compose/material/DismissValue.html"
    - title: "DrawerValue"
      path: "/reference/androidx/compose/material/DrawerValue.html"
    - title: "ModalBottomSheetValue"
      path: "/reference/androidx/compose/material/ModalBottomSheetValue.html"
    - title: "SnackbarDuration"
      path: "/reference/androidx/compose/material/SnackbarDuration.html"
    - title: "SnackbarResult"
      path: "/reference/androidx/compose/material/SnackbarResult.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalMaterialApi"
      path: "/reference/androidx/compose/material/ExperimentalMaterialApi.html"

- title: "androidx.compose.material.icons"
  path: "/reference/androidx/compose/material/icons/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "IconsKt"
      path: "/reference/androidx/compose/material/icons/IconsKt.html"

- title: "androidx.compose.material.ripple"
  path: "/reference/androidx/compose/material/ripple/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "RippleTheme"
      path: "/reference/androidx/compose/material/ripple/RippleTheme.html"

  - title: "Classes"

    section:
    - title: "RippleAlpha"
      path: "/reference/androidx/compose/material/ripple/RippleAlpha.html"
    - title: "RippleKt"
      path: "/reference/androidx/compose/material/ripple/RippleKt.html"
    - title: "RippleThemeKt"
      path: "/reference/androidx/compose/material/ripple/RippleThemeKt.html"

- title: "androidx.compose.runtime"
  path: "/reference/androidx/compose/runtime/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Applier"
      path: "/reference/androidx/compose/runtime/Applier.html"
    - title: "Composer"
      path: "/reference/androidx/compose/runtime/Composer.html"
    - title: "Composition"
      path: "/reference/androidx/compose/runtime/Composition.html"
    - title: "ControlledComposition"
      path: "/reference/androidx/compose/runtime/ControlledComposition.html"
    - title: "DisposableEffectResult"
      path: "/reference/androidx/compose/runtime/DisposableEffectResult.html"
    - title: "MonotonicFrameClock"
      path: "/reference/androidx/compose/runtime/MonotonicFrameClock.html"
    - title: "MutableState"
      path: "/reference/androidx/compose/runtime/MutableState.html"
    - title: "ProduceStateScope"
      path: "/reference/androidx/compose/runtime/ProduceStateScope.html"
    - title: "RecomposeScope"
      path: "/reference/androidx/compose/runtime/RecomposeScope.html"
    - title: "RecomposerInfo"
      path: "/reference/androidx/compose/runtime/RecomposerInfo.html"
    - title: "RememberObserver"
      path: "/reference/androidx/compose/runtime/RememberObserver.html"
    - title: "ScopeUpdateScope"
      path: "/reference/androidx/compose/runtime/ScopeUpdateScope.html"
    - title: "SnapshotMutationPolicy"
      path: "/reference/androidx/compose/runtime/SnapshotMutationPolicy.html"
    - title: "State"
      path: "/reference/androidx/compose/runtime/State.html"

  - title: "Classes"

    section:
    - title: "AbstractApplier"
      path: "/reference/androidx/compose/runtime/AbstractApplier.html"
    - title: "ActualAndroidKt"
      path: "/reference/androidx/compose/runtime/ActualAndroidKt.html"
    - title: "AtomicReference"
      path: "/reference/androidx/compose/runtime/AtomicReference.html"
    - title: "BroadcastFrameClock"
      path: "/reference/androidx/compose/runtime/BroadcastFrameClock.html"
    - title: "ComposablesKt"
      path: "/reference/androidx/compose/runtime/ComposablesKt.html"
    - title: "ComposerKt"
      path: "/reference/androidx/compose/runtime/ComposerKt.html"
    - title: "CompositionContext"
      path: "/reference/androidx/compose/runtime/CompositionContext.html"
    - title: "CompositionKt"
      path: "/reference/androidx/compose/runtime/CompositionKt.html"
    - title: "CompositionLocal"
      path: "/reference/androidx/compose/runtime/CompositionLocal.html"
    - title: "CompositionLocalKt"
      path: "/reference/androidx/compose/runtime/CompositionLocalKt.html"
    - title: "DisposableEffectScope"
      path: "/reference/androidx/compose/runtime/DisposableEffectScope.html"
    - title: "EffectsKt"
      path: "/reference/androidx/compose/runtime/EffectsKt.html"
    - title: "ExpectKt"
      path: "/reference/androidx/compose/runtime/ExpectKt.html"
    - title: "MonotonicFrameClockKt"
      path: "/reference/androidx/compose/runtime/MonotonicFrameClockKt.html"
    - title: "PausableMonotonicFrameClock"
      path: "/reference/androidx/compose/runtime/PausableMonotonicFrameClock.html"
    - title: "ProvidableCompositionLocal"
      path: "/reference/androidx/compose/runtime/ProvidableCompositionLocal.html"
    - title: "ProvidedValue"
      path: "/reference/androidx/compose/runtime/ProvidedValue.html"
    - title: "Recomposer"
      path: "/reference/androidx/compose/runtime/Recomposer.html"
    - title: "RecomposerKt"
      path: "/reference/androidx/compose/runtime/RecomposerKt.html"
    - title: "SkippableUpdater"
      path: "/reference/androidx/compose/runtime/SkippableUpdater.html"
    - title: "SnapshotStateKt"
      path: "/reference/androidx/compose/runtime/SnapshotStateKt.html"
    - title: "Updater"
      path: "/reference/androidx/compose/runtime/Updater.html"

  - title: "Enums"

    section:
    - title: "Recomposer.State"
      path: "/reference/androidx/compose/runtime/Recomposer.State.html"

  - title: "Annotations"

    section:
    - title: "CheckResult"
      path: "/reference/androidx/compose/runtime/CheckResult.html"
    - title: "Composable"
      path: "/reference/androidx/compose/runtime/Composable.html"
    - title: "ComposeCompilerApi"
      path: "/reference/androidx/compose/runtime/ComposeCompilerApi.html"
    - title: "DisallowComposableCalls"
      path: "/reference/androidx/compose/runtime/DisallowComposableCalls.html"
    - title: "ExperimentalComposeApi"
      path: "/reference/androidx/compose/runtime/ExperimentalComposeApi.html"
    - title: "ExplicitGroupsComposable"
      path: "/reference/androidx/compose/runtime/ExplicitGroupsComposable.html"
    - title: "Immutable"
      path: "/reference/androidx/compose/runtime/Immutable.html"
    - title: "InternalComposeApi"
      path: "/reference/androidx/compose/runtime/InternalComposeApi.html"
    - title: "NoLiveLiterals"
      path: "/reference/androidx/compose/runtime/NoLiveLiterals.html"
    - title: "NonRestartableComposable"
      path: "/reference/androidx/compose/runtime/NonRestartableComposable.html"
    - title: "ReadOnlyComposable"
      path: "/reference/androidx/compose/runtime/ReadOnlyComposable.html"
    - title: "Stable"
      path: "/reference/androidx/compose/runtime/Stable.html"
    - title: "StableMarker"
      path: "/reference/androidx/compose/runtime/StableMarker.html"
    - title: "TestOnly"
      path: "/reference/androidx/compose/runtime/TestOnly.html"

- title: "androidx.compose.runtime.collection"
  path: "/reference/androidx/compose/runtime/collection/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "MutableVector"
      path: "/reference/androidx/compose/runtime/collection/MutableVector.html"
    - title: "MutableVectorKt"
      path: "/reference/androidx/compose/runtime/collection/MutableVectorKt.html"

- title: "androidx.compose.runtime.livedata"
  path: "/reference/androidx/compose/runtime/livedata/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "LiveDataAdapterKt"
      path: "/reference/androidx/compose/runtime/livedata/LiveDataAdapterKt.html"

- title: "androidx.compose.runtime.rxjava2"
  path: "/reference/androidx/compose/runtime/rxjava2/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "RxJava2AdapterKt"
      path: "/reference/androidx/compose/runtime/rxjava2/RxJava2AdapterKt.html"

- title: "androidx.compose.runtime.rxjava3"
  path: "/reference/androidx/compose/runtime/rxjava3/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "RxJava3AdapterKt"
      path: "/reference/androidx/compose/runtime/rxjava3/RxJava3AdapterKt.html"

- title: "androidx.compose.runtime.saveable"
  path: "/reference/androidx/compose/runtime/saveable/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "SaveableStateHolder"
      path: "/reference/androidx/compose/runtime/saveable/SaveableStateHolder.html"
    - title: "SaveableStateRegistry"
      path: "/reference/androidx/compose/runtime/saveable/SaveableStateRegistry.html"
    - title: "SaveableStateRegistry.Entry"
      path: "/reference/androidx/compose/runtime/saveable/SaveableStateRegistry.Entry.html"
    - title: "Saver"
      path: "/reference/androidx/compose/runtime/saveable/Saver.html"
    - title: "SaverScope"
      path: "/reference/androidx/compose/runtime/saveable/SaverScope.html"

  - title: "Classes"

    section:
    - title: "ListSaverKt"
      path: "/reference/androidx/compose/runtime/saveable/ListSaverKt.html"
    - title: "MapSaverKt"
      path: "/reference/androidx/compose/runtime/saveable/MapSaverKt.html"
    - title: "RememberSaveableKt"
      path: "/reference/androidx/compose/runtime/saveable/RememberSaveableKt.html"
    - title: "SaveableStateHolderKt"
      path: "/reference/androidx/compose/runtime/saveable/SaveableStateHolderKt.html"
    - title: "SaveableStateRegistryKt"
      path: "/reference/androidx/compose/runtime/saveable/SaveableStateRegistryKt.html"
    - title: "SaverKt"
      path: "/reference/androidx/compose/runtime/saveable/SaverKt.html"

- title: "androidx.compose.runtime.snapshots"
  path: "/reference/androidx/compose/runtime/snapshots/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "ObserverHandle"
      path: "/reference/androidx/compose/runtime/snapshots/ObserverHandle.html"
    - title: "SnapshotMutableState"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotMutableState.html"
    - title: "StateObject"
      path: "/reference/androidx/compose/runtime/snapshots/StateObject.html"

  - title: "Classes"

    section:
    - title: "MutableSnapshot"
      path: "/reference/androidx/compose/runtime/snapshots/MutableSnapshot.html"
    - title: "Snapshot"
      path: "/reference/androidx/compose/runtime/snapshots/Snapshot.html"
    - title: "SnapshotApplyResult"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotApplyResult.html"
    - title: "SnapshotApplyResult.Failure"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotApplyResult.Failure.html"
    - title: "SnapshotKt"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotKt.html"
    - title: "SnapshotStateList"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotStateList.html"
    - title: "SnapshotStateMap"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotStateMap.html"
    - title: "SnapshotStateObserver"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotStateObserver.html"
    - title: "StateRecord"
      path: "/reference/androidx/compose/runtime/snapshots/StateRecord.html"

  - title: "Exceptions"

    section:
    - title: "SnapshotApplyConflictException"
      path: "/reference/androidx/compose/runtime/snapshots/SnapshotApplyConflictException.html"

- title: "androidx.compose.runtime.tooling"
  path: "/reference/androidx/compose/runtime/tooling/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "CompositionData"
      path: "/reference/androidx/compose/runtime/tooling/CompositionData.html"
    - title: "CompositionGroup"
      path: "/reference/androidx/compose/runtime/tooling/CompositionGroup.html"

  - title: "Classes"

    section:
    - title: "InspectionTablesKt"
      path: "/reference/androidx/compose/runtime/tooling/InspectionTablesKt.html"

