toc:
- title: "Class Index"
  path: "/reference/kotlin/androidx/classes.html"

- title: "Package Index"
  path: "/reference/kotlin/androidx/packages.html"

- title: "androidx.compose.animation"
  path: "/reference/kotlin/androidx/compose/animation/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "AnimatedVisibilityScope"
      path: "/reference/kotlin/androidx/compose/animation/AnimatedVisibilityScope.html"
    - title: "SizeTransform"
      path: "/reference/kotlin/androidx/compose/animation/SizeTransform.html"

  - title: "Classes"

    section:
    - title: "AnimatedContentScope"
      path: "/reference/kotlin/androidx/compose/animation/AnimatedContentScope.html"
    - title: "AnimatedContentScope.SlideDirection"
      path: "/reference/kotlin/androidx/compose/animation/AnimatedContentScope.SlideDirection.html"
    - title: "ContentTransform"
      path: "/reference/kotlin/androidx/compose/animation/ContentTransform.html"
    - title: "EnterTransition"
      path: "/reference/kotlin/androidx/compose/animation/EnterTransition.html"
    - title: "ExitTransition"
      path: "/reference/kotlin/androidx/compose/animation/ExitTransition.html"
    - title: "SplineBasedFloatDecayAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/SplineBasedFloatDecayAnimationSpec.html"

  - title: "Enums"

    section:
    - title: "EnterExitState"
      path: "/reference/kotlin/androidx/compose/animation/EnterExitState.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalAnimationApi"
      path: "/reference/kotlin/androidx/compose/animation/ExperimentalAnimationApi.html"

- title: "androidx.compose.animation.core"
  path: "/reference/kotlin/androidx/compose/animation/core/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Animation"
      path: "/reference/kotlin/androidx/compose/animation/core/Animation.html"
    - title: "AnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationSpec.html"
    - title: "DecayAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/DecayAnimationSpec.html"
    - title: "DurationBasedAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/DurationBasedAnimationSpec.html"
    - title: "Easing"
      path: "/reference/kotlin/androidx/compose/animation/core/Easing.html"
    - title: "FiniteAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/FiniteAnimationSpec.html"
    - title: "FloatAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/FloatAnimationSpec.html"
    - title: "FloatDecayAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/FloatDecayAnimationSpec.html"
    - title: "InfiniteAnimationPolicy"
      path: "/reference/kotlin/androidx/compose/animation/core/InfiniteAnimationPolicy.html"
    - title: "Transition.Segment"
      path: "/reference/kotlin/androidx/compose/animation/core/Transition.Segment.html"
    - title: "TwoWayConverter"
      path: "/reference/kotlin/androidx/compose/animation/core/TwoWayConverter.html"
    - title: "VectorizedAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedAnimationSpec.html"
    - title: "VectorizedDecayAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedDecayAnimationSpec.html"
    - title: "VectorizedDurationBasedAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedDurationBasedAnimationSpec.html"
    - title: "VectorizedFiniteAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedFiniteAnimationSpec.html"

  - title: "Classes"

    section:
    - title: "Animatable"
      path: "/reference/kotlin/androidx/compose/animation/core/Animatable.html"
    - title: "AnimationResult"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationResult.html"
    - title: "AnimationScope"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationScope.html"
    - title: "AnimationState"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationState.html"
    - title: "AnimationVector"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationVector.html"
    - title: "AnimationVector1D"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationVector1D.html"
    - title: "AnimationVector2D"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationVector2D.html"
    - title: "AnimationVector3D"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationVector3D.html"
    - title: "AnimationVector4D"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationVector4D.html"
    - title: "AtomicReference"
      path: "/reference/kotlin/androidx/compose/animation/core/AtomicReference.html"
    - title: "CubicBezierEasing"
      path: "/reference/kotlin/androidx/compose/animation/core/CubicBezierEasing.html"
    - title: "DecayAnimation"
      path: "/reference/kotlin/androidx/compose/animation/core/DecayAnimation.html"
    - title: "FloatExponentialDecaySpec"
      path: "/reference/kotlin/androidx/compose/animation/core/FloatExponentialDecaySpec.html"
    - title: "FloatSpringSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/FloatSpringSpec.html"
    - title: "FloatTweenSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/FloatTweenSpec.html"
    - title: "InfiniteRepeatableSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/InfiniteRepeatableSpec.html"
    - title: "InfiniteTransition"
      path: "/reference/kotlin/androidx/compose/animation/core/InfiniteTransition.html"
    - title: "KeyframesSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/KeyframesSpec.html"
    - title: "KeyframesSpec.KeyframeEntity"
      path: "/reference/kotlin/androidx/compose/animation/core/KeyframesSpec.KeyframeEntity.html"
    - title: "KeyframesSpec.KeyframesSpecConfig"
      path: "/reference/kotlin/androidx/compose/animation/core/KeyframesSpec.KeyframesSpecConfig.html"
    - title: "MutableTransitionState"
      path: "/reference/kotlin/androidx/compose/animation/core/MutableTransitionState.html"
    - title: "RepeatableSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/RepeatableSpec.html"
    - title: "SnapSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/SnapSpec.html"
    - title: "SpringSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/SpringSpec.html"
    - title: "TargetBasedAnimation"
      path: "/reference/kotlin/androidx/compose/animation/core/TargetBasedAnimation.html"
    - title: "Transition"
      path: "/reference/kotlin/androidx/compose/animation/core/Transition.html"
    - title: "TweenSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/TweenSpec.html"
    - title: "VectorizedFloatAnimationSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedFloatAnimationSpec.html"
    - title: "VectorizedInfiniteRepeatableSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedInfiniteRepeatableSpec.html"
    - title: "VectorizedKeyframesSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedKeyframesSpec.html"
    - title: "VectorizedRepeatableSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedRepeatableSpec.html"
    - title: "VectorizedSnapSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedSnapSpec.html"
    - title: "VectorizedSpringSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedSpringSpec.html"
    - title: "VectorizedTweenSpec"
      path: "/reference/kotlin/androidx/compose/animation/core/VectorizedTweenSpec.html"

  - title: "Enums"

    section:
    - title: "AnimationEndReason"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationEndReason.html"
    - title: "RepeatMode"
      path: "/reference/kotlin/androidx/compose/animation/core/RepeatMode.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalTransitionApi"
      path: "/reference/kotlin/androidx/compose/animation/core/ExperimentalTransitionApi.html"
    - title: "InternalAnimationApi"
      path: "/reference/kotlin/androidx/compose/animation/core/InternalAnimationApi.html"

  - title: "Objects"

    section:
    - title: "AnimationConstants"
      path: "/reference/kotlin/androidx/compose/animation/core/AnimationConstants.html"
    - title: "Spring"
      path: "/reference/kotlin/androidx/compose/animation/core/Spring.html"

- title: "androidx.compose.foundation"
  path: "/reference/kotlin/androidx/compose/foundation/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Indication"
      path: "/reference/kotlin/androidx/compose/foundation/Indication.html"
    - title: "IndicationInstance"
      path: "/reference/kotlin/androidx/compose/foundation/IndicationInstance.html"

  - title: "Classes"

    section:
    - title: "AtomicLong"
      path: "/reference/kotlin/androidx/compose/foundation/AtomicLong.html"
    - title: "AtomicReference"
      path: "/reference/kotlin/androidx/compose/foundation/AtomicReference.html"
    - title: "BorderStroke"
      path: "/reference/kotlin/androidx/compose/foundation/BorderStroke.html"
    - title: "MutatorMutex"
      path: "/reference/kotlin/androidx/compose/foundation/MutatorMutex.html"
    - title: "ScrollState"
      path: "/reference/kotlin/androidx/compose/foundation/ScrollState.html"
    - title: "SomeJavaFile"
      path: "/reference/kotlin/androidx/compose/foundation/SomeJavaFile.html"

  - title: "Enums"

    section:
    - title: "MutatePriority"
      path: "/reference/kotlin/androidx/compose/foundation/MutatePriority.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalFoundationApi"
      path: "/reference/kotlin/androidx/compose/foundation/ExperimentalFoundationApi.html"
    - title: "InternalFoundationApi"
      path: "/reference/kotlin/androidx/compose/foundation/InternalFoundationApi.html"

- title: "androidx.compose.foundation.gestures"
  path: "/reference/kotlin/androidx/compose/foundation/gestures/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "DragScope"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/DragScope.html"
    - title: "DraggableState"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/DraggableState.html"
    - title: "FlingBehavior"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/FlingBehavior.html"
    - title: "PressGestureScope"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/PressGestureScope.html"
    - title: "ScrollScope"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/ScrollScope.html"
    - title: "ScrollableState"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/ScrollableState.html"
    - title: "TransformScope"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/TransformScope.html"
    - title: "TransformableState"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/TransformableState.html"

  - title: "Enums"

    section:
    - title: "Orientation"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/Orientation.html"

  - title: "Exceptions"

    section:
    - title: "GestureCancellationException"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/GestureCancellationException.html"

  - title: "Objects"

    section:
    - title: "ScrollableDefaults"
      path: "/reference/kotlin/androidx/compose/foundation/gestures/ScrollableDefaults.html"

- title: "androidx.compose.foundation.interaction"
  path: "/reference/kotlin/androidx/compose/foundation/interaction/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "DragInteraction"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/DragInteraction.html"
    - title: "FocusInteraction"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/FocusInteraction.html"
    - title: "Interaction"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/Interaction.html"
    - title: "InteractionSource"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/InteractionSource.html"
    - title: "MutableInteractionSource"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/MutableInteractionSource.html"
    - title: "PressInteraction"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/PressInteraction.html"

  - title: "Classes"

    section:
    - title: "DragInteraction.Cancel"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/DragInteraction.Cancel.html"
    - title: "DragInteraction.Start"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/DragInteraction.Start.html"
    - title: "DragInteraction.Stop"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/DragInteraction.Stop.html"
    - title: "FocusInteraction.Focus"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/FocusInteraction.Focus.html"
    - title: "FocusInteraction.Unfocus"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/FocusInteraction.Unfocus.html"
    - title: "PressInteraction.Cancel"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/PressInteraction.Cancel.html"
    - title: "PressInteraction.Press"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/PressInteraction.Press.html"
    - title: "PressInteraction.Release"
      path: "/reference/kotlin/androidx/compose/foundation/interaction/PressInteraction.Release.html"

- title: "androidx.compose.foundation.layout"
  path: "/reference/kotlin/androidx/compose/foundation/layout/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Arrangement.Horizontal"
      path: "/reference/kotlin/androidx/compose/foundation/layout/Arrangement.Horizontal.html"
    - title: "Arrangement.HorizontalOrVertical"
      path: "/reference/kotlin/androidx/compose/foundation/layout/Arrangement.HorizontalOrVertical.html"
    - title: "Arrangement.Vertical"
      path: "/reference/kotlin/androidx/compose/foundation/layout/Arrangement.Vertical.html"
    - title: "BoxScope"
      path: "/reference/kotlin/androidx/compose/foundation/layout/BoxScope.html"
    - title: "BoxWithConstraintsScope"
      path: "/reference/kotlin/androidx/compose/foundation/layout/BoxWithConstraintsScope.html"
    - title: "ColumnScope"
      path: "/reference/kotlin/androidx/compose/foundation/layout/ColumnScope.html"
    - title: "PaddingValues"
      path: "/reference/kotlin/androidx/compose/foundation/layout/PaddingValues.html"
    - title: "RowScope"
      path: "/reference/kotlin/androidx/compose/foundation/layout/RowScope.html"

  - title: "Classes"

    section:
    - title: "PaddingValues.Absolute"
      path: "/reference/kotlin/androidx/compose/foundation/layout/PaddingValues.Absolute.html"

  - title: "Enums"

    section:
    - title: "IntrinsicSize"
      path: "/reference/kotlin/androidx/compose/foundation/layout/IntrinsicSize.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalLayoutApi"
      path: "/reference/kotlin/androidx/compose/foundation/layout/ExperimentalLayoutApi.html"
    - title: "LayoutScopeMarker"
      path: "/reference/kotlin/androidx/compose/foundation/layout/LayoutScopeMarker.html"

  - title: "Objects"

    section:
    - title: "Arrangement"
      path: "/reference/kotlin/androidx/compose/foundation/layout/Arrangement.html"
    - title: "Arrangement.Absolute"
      path: "/reference/kotlin/androidx/compose/foundation/layout/Arrangement.Absolute.html"

- title: "androidx.compose.foundation.lazy"
  path: "/reference/kotlin/androidx/compose/foundation/lazy/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "LazyGridScope"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyGridScope.html"
    - title: "LazyItemScope"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyItemScope.html"
    - title: "LazyListItemInfo"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyListItemInfo.html"
    - title: "LazyListLayoutInfo"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyListLayoutInfo.html"
    - title: "LazyListScope"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyListScope.html"

  - title: "Classes"

    section:
    - title: "GridCells"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/GridCells.html"
    - title: "GridCells.Adaptive"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/GridCells.Adaptive.html"
    - title: "GridCells.Fixed"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/GridCells.Fixed.html"
    - title: "LazyListState"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyListState.html"

  - title: "Annotations"

    section:
    - title: "LazyScopeMarker"
      path: "/reference/kotlin/androidx/compose/foundation/lazy/LazyScopeMarker.html"

- title: "androidx.compose.foundation.selection"
  path: "/reference/kotlin/androidx/compose/foundation/selection/package-summary.html"

- title: "androidx.compose.foundation.shape"
  path: "/reference/kotlin/androidx/compose/foundation/shape/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "CornerSize"
      path: "/reference/kotlin/androidx/compose/foundation/shape/CornerSize.html"

  - title: "Classes"

    section:
    - title: "AbsoluteCutCornerShape"
      path: "/reference/kotlin/androidx/compose/foundation/shape/AbsoluteCutCornerShape.html"
    - title: "AbsoluteRoundedCornerShape"
      path: "/reference/kotlin/androidx/compose/foundation/shape/AbsoluteRoundedCornerShape.html"
    - title: "CornerBasedShape"
      path: "/reference/kotlin/androidx/compose/foundation/shape/CornerBasedShape.html"
    - title: "CutCornerShape"
      path: "/reference/kotlin/androidx/compose/foundation/shape/CutCornerShape.html"
    - title: "GenericShape"
      path: "/reference/kotlin/androidx/compose/foundation/shape/GenericShape.html"
    - title: "RoundedCornerShape"
      path: "/reference/kotlin/androidx/compose/foundation/shape/RoundedCornerShape.html"

- title: "androidx.compose.foundation.text"
  path: "/reference/kotlin/androidx/compose/foundation/text/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "KeyboardActionScope"
      path: "/reference/kotlin/androidx/compose/foundation/text/KeyboardActionScope.html"

  - title: "Classes"

    section:
    - title: "InlineTextContent"
      path: "/reference/kotlin/androidx/compose/foundation/text/InlineTextContent.html"
    - title: "KeyboardActions"
      path: "/reference/kotlin/androidx/compose/foundation/text/KeyboardActions.html"
    - title: "KeyboardOptions"
      path: "/reference/kotlin/androidx/compose/foundation/text/KeyboardOptions.html"

  - title: "Annotations"

    section:
    - title: "InternalFoundationTextApi"
      path: "/reference/kotlin/androidx/compose/foundation/text/InternalFoundationTextApi.html"

- title: "androidx.compose.foundation.text.selection"
  path: "/reference/kotlin/androidx/compose/foundation/text/selection/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "TextSelectionColors"
      path: "/reference/kotlin/androidx/compose/foundation/text/selection/TextSelectionColors.html"

- title: "androidx.compose.material"
  path: "/reference/kotlin/androidx/compose/material/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "ButtonColors"
      path: "/reference/kotlin/androidx/compose/material/ButtonColors.html"
    - title: "ButtonElevation"
      path: "/reference/kotlin/androidx/compose/material/ButtonElevation.html"
    - title: "CheckboxColors"
      path: "/reference/kotlin/androidx/compose/material/CheckboxColors.html"
    - title: "ElevationOverlay"
      path: "/reference/kotlin/androidx/compose/material/ElevationOverlay.html"
    - title: "FloatingActionButtonElevation"
      path: "/reference/kotlin/androidx/compose/material/FloatingActionButtonElevation.html"
    - title: "RadioButtonColors"
      path: "/reference/kotlin/androidx/compose/material/RadioButtonColors.html"
    - title: "SliderColors"
      path: "/reference/kotlin/androidx/compose/material/SliderColors.html"
    - title: "SnackbarData"
      path: "/reference/kotlin/androidx/compose/material/SnackbarData.html"
    - title: "SwitchColors"
      path: "/reference/kotlin/androidx/compose/material/SwitchColors.html"
    - title: "TextFieldColors"
      path: "/reference/kotlin/androidx/compose/material/TextFieldColors.html"
    - title: "ThresholdConfig"
      path: "/reference/kotlin/androidx/compose/material/ThresholdConfig.html"

  - title: "Classes"

    section:
    - title: "BackdropScaffoldState"
      path: "/reference/kotlin/androidx/compose/material/BackdropScaffoldState.html"
    - title: "BottomDrawerState"
      path: "/reference/kotlin/androidx/compose/material/BottomDrawerState.html"
    - title: "BottomSheetScaffoldState"
      path: "/reference/kotlin/androidx/compose/material/BottomSheetScaffoldState.html"
    - title: "BottomSheetState"
      path: "/reference/kotlin/androidx/compose/material/BottomSheetState.html"
    - title: "Colors"
      path: "/reference/kotlin/androidx/compose/material/Colors.html"
    - title: "DismissState"
      path: "/reference/kotlin/androidx/compose/material/DismissState.html"
    - title: "DrawerState"
      path: "/reference/kotlin/androidx/compose/material/DrawerState.html"
    - title: "FabPosition"
      path: "/reference/kotlin/androidx/compose/material/FabPosition.html"
    - title: "FixedThreshold"
      path: "/reference/kotlin/androidx/compose/material/FixedThreshold.html"
    - title: "FractionalThreshold"
      path: "/reference/kotlin/androidx/compose/material/FractionalThreshold.html"
    - title: "ModalBottomSheetState"
      path: "/reference/kotlin/androidx/compose/material/ModalBottomSheetState.html"
    - title: "ResistanceConfig"
      path: "/reference/kotlin/androidx/compose/material/ResistanceConfig.html"
    - title: "ScaffoldState"
      path: "/reference/kotlin/androidx/compose/material/ScaffoldState.html"
    - title: "Shapes"
      path: "/reference/kotlin/androidx/compose/material/Shapes.html"
    - title: "SnackbarHostState"
      path: "/reference/kotlin/androidx/compose/material/SnackbarHostState.html"
    - title: "SwipeProgress"
      path: "/reference/kotlin/androidx/compose/material/SwipeProgress.html"
    - title: "SwipeableState"
      path: "/reference/kotlin/androidx/compose/material/SwipeableState.html"
    - title: "TabPosition"
      path: "/reference/kotlin/androidx/compose/material/TabPosition.html"
    - title: "Typography"
      path: "/reference/kotlin/androidx/compose/material/Typography.html"

  - title: "Enums"

    section:
    - title: "BackdropValue"
      path: "/reference/kotlin/androidx/compose/material/BackdropValue.html"
    - title: "BottomDrawerValue"
      path: "/reference/kotlin/androidx/compose/material/BottomDrawerValue.html"
    - title: "BottomSheetValue"
      path: "/reference/kotlin/androidx/compose/material/BottomSheetValue.html"
    - title: "DismissDirection"
      path: "/reference/kotlin/androidx/compose/material/DismissDirection.html"
    - title: "DismissValue"
      path: "/reference/kotlin/androidx/compose/material/DismissValue.html"
    - title: "DrawerValue"
      path: "/reference/kotlin/androidx/compose/material/DrawerValue.html"
    - title: "ModalBottomSheetValue"
      path: "/reference/kotlin/androidx/compose/material/ModalBottomSheetValue.html"
    - title: "SnackbarDuration"
      path: "/reference/kotlin/androidx/compose/material/SnackbarDuration.html"
    - title: "SnackbarResult"
      path: "/reference/kotlin/androidx/compose/material/SnackbarResult.html"

  - title: "Annotations"

    section:
    - title: "ExperimentalMaterialApi"
      path: "/reference/kotlin/androidx/compose/material/ExperimentalMaterialApi.html"

  - title: "Objects"

    section:
    - title: "AppBarDefaults"
      path: "/reference/kotlin/androidx/compose/material/AppBarDefaults.html"
    - title: "BackdropScaffoldDefaults"
      path: "/reference/kotlin/androidx/compose/material/BackdropScaffoldDefaults.html"
    - title: "BottomNavigationDefaults"
      path: "/reference/kotlin/androidx/compose/material/BottomNavigationDefaults.html"
    - title: "BottomSheetScaffoldDefaults"
      path: "/reference/kotlin/androidx/compose/material/BottomSheetScaffoldDefaults.html"
    - title: "ButtonDefaults"
      path: "/reference/kotlin/androidx/compose/material/ButtonDefaults.html"
    - title: "CheckboxDefaults"
      path: "/reference/kotlin/androidx/compose/material/CheckboxDefaults.html"
    - title: "ContentAlpha"
      path: "/reference/kotlin/androidx/compose/material/ContentAlpha.html"
    - title: "DrawerDefaults"
      path: "/reference/kotlin/androidx/compose/material/DrawerDefaults.html"
    - title: "FloatingActionButtonDefaults"
      path: "/reference/kotlin/androidx/compose/material/FloatingActionButtonDefaults.html"
    - title: "MaterialTheme"
      path: "/reference/kotlin/androidx/compose/material/MaterialTheme.html"
    - title: "MenuDefaults"
      path: "/reference/kotlin/androidx/compose/material/MenuDefaults.html"
    - title: "ModalBottomSheetDefaults"
      path: "/reference/kotlin/androidx/compose/material/ModalBottomSheetDefaults.html"
    - title: "ProgressIndicatorDefaults"
      path: "/reference/kotlin/androidx/compose/material/ProgressIndicatorDefaults.html"
    - title: "RadioButtonDefaults"
      path: "/reference/kotlin/androidx/compose/material/RadioButtonDefaults.html"
    - title: "SliderDefaults"
      path: "/reference/kotlin/androidx/compose/material/SliderDefaults.html"
    - title: "SnackbarDefaults"
      path: "/reference/kotlin/androidx/compose/material/SnackbarDefaults.html"
    - title: "SwipeableDefaults"
      path: "/reference/kotlin/androidx/compose/material/SwipeableDefaults.html"
    - title: "SwitchDefaults"
      path: "/reference/kotlin/androidx/compose/material/SwitchDefaults.html"
    - title: "TabRowDefaults"
      path: "/reference/kotlin/androidx/compose/material/TabRowDefaults.html"
    - title: "TextFieldDefaults"
      path: "/reference/kotlin/androidx/compose/material/TextFieldDefaults.html"

- title: "androidx.compose.material.icons"
  path: "/reference/kotlin/androidx/compose/material/icons/package-summary.html"

  section:
  - title: "Objects"

    section:
    - title: "Icons"
      path: "/reference/kotlin/androidx/compose/material/icons/Icons.html"
    - title: "Icons.Filled"
      path: "/reference/kotlin/androidx/compose/material/icons/Icons.Filled.html"
    - title: "Icons.Outlined"
      path: "/reference/kotlin/androidx/compose/material/icons/Icons.Outlined.html"
    - title: "Icons.Rounded"
      path: "/reference/kotlin/androidx/compose/material/icons/Icons.Rounded.html"
    - title: "Icons.Sharp"
      path: "/reference/kotlin/androidx/compose/material/icons/Icons.Sharp.html"
    - title: "Icons.TwoTone"
      path: "/reference/kotlin/androidx/compose/material/icons/Icons.TwoTone.html"

- title: "androidx.compose.material.ripple"
  path: "/reference/kotlin/androidx/compose/material/ripple/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "RippleTheme"
      path: "/reference/kotlin/androidx/compose/material/ripple/RippleTheme.html"

  - title: "Classes"

    section:
    - title: "RippleAlpha"
      path: "/reference/kotlin/androidx/compose/material/ripple/RippleAlpha.html"

- title: "androidx.compose.runtime"
  path: "/reference/kotlin/androidx/compose/runtime/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "Applier"
      path: "/reference/kotlin/androidx/compose/runtime/Applier.html"
    - title: "Composer"
      path: "/reference/kotlin/androidx/compose/runtime/Composer.html"
    - title: "Composition"
      path: "/reference/kotlin/androidx/compose/runtime/Composition.html"
    - title: "ControlledComposition"
      path: "/reference/kotlin/androidx/compose/runtime/ControlledComposition.html"
    - title: "DisposableEffectResult"
      path: "/reference/kotlin/androidx/compose/runtime/DisposableEffectResult.html"
    - title: "MonotonicFrameClock"
      path: "/reference/kotlin/androidx/compose/runtime/MonotonicFrameClock.html"
    - title: "MutableState"
      path: "/reference/kotlin/androidx/compose/runtime/MutableState.html"
    - title: "ProduceStateScope"
      path: "/reference/kotlin/androidx/compose/runtime/ProduceStateScope.html"
    - title: "RecomposeScope"
      path: "/reference/kotlin/androidx/compose/runtime/RecomposeScope.html"
    - title: "RecomposerInfo"
      path: "/reference/kotlin/androidx/compose/runtime/RecomposerInfo.html"
    - title: "RememberObserver"
      path: "/reference/kotlin/androidx/compose/runtime/RememberObserver.html"
    - title: "ScopeUpdateScope"
      path: "/reference/kotlin/androidx/compose/runtime/ScopeUpdateScope.html"
    - title: "SnapshotMutationPolicy"
      path: "/reference/kotlin/androidx/compose/runtime/SnapshotMutationPolicy.html"
    - title: "State"
      path: "/reference/kotlin/androidx/compose/runtime/State.html"

  - title: "Classes"

    section:
    - title: "AbstractApplier"
      path: "/reference/kotlin/androidx/compose/runtime/AbstractApplier.html"
    - title: "AtomicReference"
      path: "/reference/kotlin/androidx/compose/runtime/AtomicReference.html"
    - title: "BroadcastFrameClock"
      path: "/reference/kotlin/androidx/compose/runtime/BroadcastFrameClock.html"
    - title: "CompositionContext"
      path: "/reference/kotlin/androidx/compose/runtime/CompositionContext.html"
    - title: "CompositionLocal"
      path: "/reference/kotlin/androidx/compose/runtime/CompositionLocal.html"
    - title: "DisposableEffectScope"
      path: "/reference/kotlin/androidx/compose/runtime/DisposableEffectScope.html"
    - title: "PausableMonotonicFrameClock"
      path: "/reference/kotlin/androidx/compose/runtime/PausableMonotonicFrameClock.html"
    - title: "ProvidableCompositionLocal"
      path: "/reference/kotlin/androidx/compose/runtime/ProvidableCompositionLocal.html"
    - title: "ProvidedValue"
      path: "/reference/kotlin/androidx/compose/runtime/ProvidedValue.html"
    - title: "Recomposer"
      path: "/reference/kotlin/androidx/compose/runtime/Recomposer.html"
    - title: "SkippableUpdater"
      path: "/reference/kotlin/androidx/compose/runtime/SkippableUpdater.html"
    - title: "Updater"
      path: "/reference/kotlin/androidx/compose/runtime/Updater.html"

  - title: "Enums"

    section:
    - title: "Recomposer.State"
      path: "/reference/kotlin/androidx/compose/runtime/Recomposer.State.html"

  - title: "Annotations"

    section:
    - title: "CheckResult"
      path: "/reference/kotlin/androidx/compose/runtime/CheckResult.html"
    - title: "Composable"
      path: "/reference/kotlin/androidx/compose/runtime/Composable.html"
    - title: "ComposeCompilerApi"
      path: "/reference/kotlin/androidx/compose/runtime/ComposeCompilerApi.html"
    - title: "DisallowComposableCalls"
      path: "/reference/kotlin/androidx/compose/runtime/DisallowComposableCalls.html"
    - title: "ExperimentalComposeApi"
      path: "/reference/kotlin/androidx/compose/runtime/ExperimentalComposeApi.html"
    - title: "ExplicitGroupsComposable"
      path: "/reference/kotlin/androidx/compose/runtime/ExplicitGroupsComposable.html"
    - title: "Immutable"
      path: "/reference/kotlin/androidx/compose/runtime/Immutable.html"
    - title: "InternalComposeApi"
      path: "/reference/kotlin/androidx/compose/runtime/InternalComposeApi.html"
    - title: "NoLiveLiterals"
      path: "/reference/kotlin/androidx/compose/runtime/NoLiveLiterals.html"
    - title: "NonRestartableComposable"
      path: "/reference/kotlin/androidx/compose/runtime/NonRestartableComposable.html"
    - title: "ReadOnlyComposable"
      path: "/reference/kotlin/androidx/compose/runtime/ReadOnlyComposable.html"
    - title: "Stable"
      path: "/reference/kotlin/androidx/compose/runtime/Stable.html"
    - title: "StableMarker"
      path: "/reference/kotlin/androidx/compose/runtime/StableMarker.html"
    - title: "TestOnly"
      path: "/reference/kotlin/androidx/compose/runtime/TestOnly.html"

- title: "androidx.compose.runtime.collection"
  path: "/reference/kotlin/androidx/compose/runtime/collection/package-summary.html"

  section:
  - title: "Classes"

    section:
    - title: "MutableVector"
      path: "/reference/kotlin/androidx/compose/runtime/collection/MutableVector.html"

- title: "androidx.compose.runtime.livedata"
  path: "/reference/kotlin/androidx/compose/runtime/livedata/package-summary.html"

- title: "androidx.compose.runtime.rxjava2"
  path: "/reference/kotlin/androidx/compose/runtime/rxjava2/package-summary.html"

- title: "androidx.compose.runtime.rxjava3"
  path: "/reference/kotlin/androidx/compose/runtime/rxjava3/package-summary.html"

- title: "androidx.compose.runtime.saveable"
  path: "/reference/kotlin/androidx/compose/runtime/saveable/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "SaveableStateHolder"
      path: "/reference/kotlin/androidx/compose/runtime/saveable/SaveableStateHolder.html"
    - title: "SaveableStateRegistry"
      path: "/reference/kotlin/androidx/compose/runtime/saveable/SaveableStateRegistry.html"
    - title: "SaveableStateRegistry.Entry"
      path: "/reference/kotlin/androidx/compose/runtime/saveable/SaveableStateRegistry.Entry.html"
    - title: "Saver"
      path: "/reference/kotlin/androidx/compose/runtime/saveable/Saver.html"
    - title: "SaverScope"
      path: "/reference/kotlin/androidx/compose/runtime/saveable/SaverScope.html"

- title: "androidx.compose.runtime.snapshots"
  path: "/reference/kotlin/androidx/compose/runtime/snapshots/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "ObserverHandle"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/ObserverHandle.html"
    - title: "SnapshotMutableState"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotMutableState.html"
    - title: "StateObject"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/StateObject.html"

  - title: "Classes"

    section:
    - title: "MutableSnapshot"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/MutableSnapshot.html"
    - title: "Snapshot"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/Snapshot.html"
    - title: "SnapshotApplyResult"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotApplyResult.html"
    - title: "SnapshotApplyResult.Failure"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotApplyResult.Failure.html"
    - title: "SnapshotStateList"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotStateList.html"
    - title: "SnapshotStateMap"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotStateMap.html"
    - title: "SnapshotStateObserver"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotStateObserver.html"
    - title: "StateRecord"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/StateRecord.html"

  - title: "Exceptions"

    section:
    - title: "SnapshotApplyConflictException"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotApplyConflictException.html"

  - title: "Objects"

    section:
    - title: "SnapshotApplyResult.Success"
      path: "/reference/kotlin/androidx/compose/runtime/snapshots/SnapshotApplyResult.Success.html"

- title: "androidx.compose.runtime.tooling"
  path: "/reference/kotlin/androidx/compose/runtime/tooling/package-summary.html"

  section:
  - title: "Interfaces"

    section:
    - title: "CompositionData"
      path: "/reference/kotlin/androidx/compose/runtime/tooling/CompositionData.html"
    - title: "CompositionGroup"
      path: "/reference/kotlin/androidx/compose/runtime/tooling/CompositionGroup.html"

